version: "3"
services:

  zookeeper:
    image: eventuateio/eventuateio-local-zookeeper:${eventuateLocalVersion}
    container_name: zookeeper
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  kafka:
    image: eventuateio/eventuateio-local-kafka:${eventuateLocalVersion}
    container_name: kafka
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ADVERTISED_HOST_NAME=${DOCKER_HOST_IP}
      - KAFKA_HEAP_OPTS=-Xmx320m -Xms320m
      - ZOOKEEPER_SERVERS=zookeeper:2181

  mysql:
    build: ./mysql
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw

  mongo:
    image: mongo:3.4.6
    container_name: query_db
    ports:
      - "27017:27017"

  cdcservice:
    image: eventuateio/eventuateio-local-new-cdc-service:${eventuateLocalVersion}
    container_name: cdcservice
    ports:
      - "8099:8080"
    links:
      - mysql
      - kafka
      - zookeeper
    environment:
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      EVENTUATE_CDC_PIPELINE_PROPERTIES: >
        [{"type":"eventuate-local",
        "reader":"reader1"}]
      EVENTUATE_CDC_PIPELINE_READER_PROPERTIES: >
        [{"type":"mysql-binlog",
        "name":"reader1",
        "dataSourceUrl":"jdbc:mysql://mysql:3306/eventuate",
        "dataSourceUserName":"mysqluser",
        "dataSourcePassword":"mysqlpw",
        "dataSourceDriverClassName":"com.mysql.jdbc.Driver",
        "leadershipLockPath":"/eventuatelocal/cdc/leader/pipeline/1",
        "binlogClientId": 1,
        "cdcDbUserName":"root",
        "cdcDbPassword":"rootpassword",
        "oldDebeziumDbHistoryTopicName":"none"}]

  configservice:
    image: tawcd.stc.com.sa/supportservices/configservice:22
    container_name: config_service
    ports:
      - "8888:8888"

#  configservice:
#      image: tawcd.stc.com.sa/config-prod
#      container_name: config_service
#      ports:
#          - "8888:8888"
#      environment:
#          - TZ=Asia/Riyadh
#          - SPRING_PROFILES_ACTIVE=prod

  crmuserservice:
    image: tawcd.stc.com.sa/crmadapter-r0-02
    container_name: crm_users_adapter
    links:
      - mysql
    ports:
      - "1445:1445"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_CONFIG_URI=http://configservice:8888

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 6002:8080

#
#  mongoui:
#    container_name: adminMongo
#    image: tawcd.stc.com.sa/mongoui_prod_02
#    ports:
#            - "6006:6003"
#    volumes:
#    - mongouiVolume:/var/lib/docker/volumes/mongouiVolume/_data
#
#volumes:
#  mongouiVolume:
#    driver: local
#    #external: true

#  bosdatabase:
#    build: ./bosDatabase
#    image: mysql
#    container_name: bos_database
#    #        volumes:
#    #            - notificationDatabase:/var/lib/mysql
#    environment:
#      - MYSQL_ROOT_PASSWORD=rootpassword
#      - MYSQL_DATABASE=bosDB
#    ports:
#      - "3306:3306"
#  authorizationservice:
#      image: tawcd.stc.com.sa/auth-r6-01
#      container_name: authorization_service
#      ports:
#          - "8181:8181"
#      environment:
#          - SPRING_CLOUD_CONFIG_URI=http://configservice:8888
#          - SPRING_PROFILES_ACTIVE=dev
#      links:
#          - mysql
#          - kafka
#          - zookeeper
#          - configservice

#    complaintcmdservice:
#        image: tawcd.stc.com.sa/cc-r6-03
#        container_name: complaint_command_service
#        ports:
#            - "9711:9711"
#        links:
#            - mysql
#            - kafka
#            - zookeeper
#            - cdcservice
#            - configservice
#            - authorizationservice
#        environment:
#            - SPRING_PROFILES_ACTIVE=dev
#            - SPRING_CLOUD_CONFIG_URI=http://configservice:8888
#    complaintqueryservice:
#        image: tawcd.stc.com.sa/cq-r6-02
#        container_name: complaint_query_service
#        ports:
#            - "9712:9712"
#        links:
#            - mysql
#            - kafka
#            - zookeeper
#            - cdcservice
#            - configservice
#            - authorizationservice
#        environment:
#            - SPRING_PROFILES_ACTIVE=dev
#            - SPRING_CLOUD_CONFIG_URI=http://configservice:8888
#    workforcecommandservice:
#        image: tawcd.stc.com.sa/workforce-command-r6-01
#        container_name: workforce_command_service3
#        ports:
#            - "9783:9783"
#        links:
#            - mysql
#            - kafka
#            - zookeeper
#            - cdcservice
#            - configservice
#            - authorizationservice
#        environment:
#            - SPRING_PROFILES_ACTIVE=dev
#            - SPRING_CLOUD_CONFIG_URI=http://configservice:8888
#    workforcequeryservice:
#        image: tawcd.stc.com.sa/wfq2-r6-02
#        ports:
#            - "9854:9854"
#        container_name: workforce_query_service3
#        environment:
#            - SPRING_PROFILES_ACTIVE=dev
#            - SPRING_CLOUD_CONFIG_URI=http://configservice:8888
#    reportservice:
#        image: tawcd.stc.com.sa/reportengineservice-r5
#        container_name: report_service
#        ports:
#            - "2424:2424"
#        environment:
#            - SPRING_PROFILES_ACTIVE=dev
#            - SPRING_CLOUD_CONFIG_URI=http://configservice:8888
#    notificationservie:
#        image: tawcd.stc.com.sa/notification-service-r6-01
#        container_name: notification_service
#        ports:
#            - "9863:9836"
#        environment:
#            - SPRING_PROFILES_ACTIVE=dev
#            - SPRING_CLOUD_CONFIG_URI=http://configservice:8888
#
#    assignmentservice:
#        image: tawcd.stc.com.sa/assignment-r6-02
#        ports:
#             - "8543:8543"
#        environment:
#             - SPRING_PROFILES_ACTIVE=dev
#             - SPRING_CLOUD_CONFIG_URI=http://configservice:8888
#        links:
#             - cdcservice
#             - configservice
#             - authorizationservice
#             - mysql
#             - kafka
#             - zookeeper
#    reportqueryservice:
#        image: tawcd.stc.com.sa/report-query-service-r6-01
#        ports:
#            - "4222:4222"
#        environment:
#             - SPRING_PROFILES_ACTIVE=dev
#             - SPRING_CLOUD_CONFIG_URI=http://configservice:8888
#        links:
#             - cdcservice
#             - configservice
#             - authorizationservice
#             - mysql
#             - kafka
#             - zookeeper
#
#    postgresql:
#        image: postgres
#        restart: always
#        environment:
#          POSTGRES_PASSWORD: example
#        ports:
#          - 5432:5432
#    node:
#        image: tawcd.stc.com.sa/webapp-node-r6-08-useridle
#        ports:
#            - "10001:10001"
#        extra_hosts:
#            - "workforcequeryservice:10.33.18.55"
#            - "workforcecommandservice:10.33.18.55"
#            - "complaintqueryservice:10.33.18.55"
#            - "authorizationservice:10.33.18.55"
#            - "notificationservice:10.33.18.55"
#            - "assignmentservice:10.33.18.55"
#            - "reportqueryservice:10.33.18.55"
#    phpmyadmin:
#       image: "phpmyadmin/phpmyadmin:4.7"
#       ports:
#           - "7003:80"
#       environment:
#           PMA_HOSTS: "10.33.18.80:40000,10.33.18.80:3306" # mysql url
