version: "3"
services:
  zookeeper:
    image: eventuateio/eventuateio-local-zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  kafka:
    image: eventuateio/eventuateio-local-kafka
    container_name: kafka
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ADVERTISED_HOST_NAME=${DOCKER_HOST_IP}
      - KAFKA_HEAP_OPTS=-Xmx320m -Xms320m
      - ZOOKEEPER_SERVERS=zookeeper:2181

  mysql:
    image: eventuateio/eventuateio-local-mysql:0.20.1.RELEASE
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw

  cdcservice:
    image: eventuateio/eventuateio-local-new-cdc-service
    container_name: cdcservice
    ports:
      - "8099:8080"
    links:
      - mysql
      - kafka
      - zookeeper
    environment:
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      EVENTUATE_CDC_PIPELINE_PROPERTIES: >
        [{"type":"eventuate-local",
        "reader":"reader1"}]
      EVENTUATE_CDC_PIPELINE_READER_PROPERTIES: >
        [{"type":"mysql-binlog",
        "name":"reader1",
        "dataSourceUrl":"jdbc:mysql://mysql:3306/eventuate",
        "dataSourceUserName":"mysqluser",
        "dataSourcePassword":"mysqlpw",
        "dataSourceDriverClassName":"com.mysql.jdbc.Driver",
        "leadershipLockPath":"/eventuatelocal/cdc/leader/pipeline/1",
        "binlogClientId": 1,
        "cdcDbUserName":"root",
        "cdcDbPassword":"rootpassword",
        "oldDebeziumDbHistoryTopicName":"none"}]

  mongo:
    image: mongo
    restart: always
    ports:
    - "8081:8081"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

